package constants

type KubernetesWorkload string
type KubernetesRule string

const (
	POD_WORKLOAD         KubernetesWorkload = "POD_WORKLOAD"
	JOB_WORKLOAD         KubernetesWorkload = "JOB_WORKLOAD"
	CRONJOB_WORKLOAD     KubernetesWorkload = "CRONJOB_WORKLOAD"
	REPLICASET_WORKLOAD  KubernetesWorkload = "REPLICASET_WORKLOAD"
	DEPLOYMENT_WORKLOAD  KubernetesWorkload = "DEPLOYMENT_WORKLOAD"
	DAEMONSET_WORKLOAD   KubernetesWorkload = "DAEMONSET_WORKLOAD"
	STATEFULSET_WORKLOAD KubernetesWorkload = "STATEFULSET_WORKLOAD"
)

const (
	K8S_SEC_CAPABILITIES_UNSET   KubernetesRule = "K8S_SEC_CAPABILITIES_UNSET"
	K8S_SEC_RUNASUSER_UNSET      KubernetesRule = "K8S_SEC_RUNASUSER_UNSET"
	K8S_SEC_RUNASNONROOT_UNSET   KubernetesRule = "K8S_SEC_RUNASNONROOT_UNSET"
	K8S_SEC_PRIVESCALATION_UNSET KubernetesRule = "K8S_SEC_PRIVESCALATION_UNSET"
	K8S_SEC_ROROOTFS_UNSET       KubernetesRule = "K8S_SEC_ROROOTFS_UNSET"
	// K8S_SEC_PRIVILEGED_UNSET     KubernetesRule = "K8S_SEC_PRIVILEGED_UNSET"
	K8S_SEC_RESREQUESTS_UNSET    KubernetesRule = "K8S_SEC_RESREQUESTS_UNSET"
	K8S_SEC_RESLIMITS_UNSET      KubernetesRule = "K8S_SEC_RESLIMITS_UNSET"
	K8S_SEC_CAPABILITIES_VALUE   KubernetesRule = "K8S_SEC_CAPABILITIES_VALUE"
	K8S_SEC_RUNASUSER_VALUE      KubernetesRule = "K8S_SEC_RUNASUSER_VALUE"
	K8S_SEC_RUNASNONROOT_VALUE   KubernetesRule = "K8S_SEC_RUNASNONROOT_VALUE"
	K8S_SEC_PRIVESCALATION_VALUE KubernetesRule = "K8S_SEC_PRIVESCALATION_VALUE"
	K8S_SEC_ROROOTFS_VALUE       KubernetesRule = "K8S_SEC_ROROOTFS_VALUE"
	K8S_SEC_PRIVILEGED_VALUE     KubernetesRule = "K8S_SEC_PRIVILEGED_VALUE"
)
